swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /posts:
        get:
            tags:
                - posts
            summary: list posts
            description: 記事一覧
            operationId: posts#list
            parameters:
                - name: page
                  in: query
                  description: ページ番号
                  required: false
                  type: integer
                  default: 1
                  minimum: 1
                - name: limit
                  in: query
                  description: 記事数
                  required: false
                  type: integer
                  default: 10
                  maximum: 100
                  minimum: 1
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Post'
            schemes:
                - http
        post:
            tags:
                - posts
            summary: create posts
            description: 記事作成
            operationId: posts#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/PostInput'
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/Post'
                        required:
                            - title
                            - description
            schemes:
                - http
    /posts/{postID}:
        get:
            tags:
                - posts
            summary: show posts
            description: 記事詳細の取得
            operationId: posts#show
            parameters:
                - name: postID
                  in: path
                  description: 記事のUUID
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Post'
                        required:
                            - title
                            - description
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PostsShowNotFoundResponseBody'
            schemes:
                - http
        put:
            tags:
                - posts
            summary: update posts
            description: 記事更新
            operationId: posts#update
            parameters:
                - name: postID
                  in: path
                  description: 記事のUUID
                  required: true
                  type: string
                  format: uuid
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/PostsUpdateRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Post'
                        required:
                            - title
                            - description
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PostsUpdateNotFoundResponseBody'
            schemes:
                - http
        delete:
            tags:
                - posts
            summary: delete posts
            description: 記事削除
            operationId: posts#delete
            parameters:
                - name: postID
                  in: path
                  description: 記事ID
                  required: true
                  type: string
                  format: uuid
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/PostsDeleteNotFoundResponseBody'
            schemes:
                - http
definitions:
    Post:
        title: Post
        type: object
        properties:
            description:
                type: string
                description: 説明
                example: 説明
                minLength: 1
            id:
                type: string
                description: 記事ID
                example: bcb8c0fe-70aa-4174-a4ef-5e0681ce5401
                format: uuid
            title:
                type: string
                description: タイトル
                example: タイトル
                minLength: 1
        description: 記事
        example:
            description: 説明
            id: 7780da1d-30fc-4780-942e-44ff12136f97
            title: タイトル
        required:
            - title
            - description
    PostInput:
        title: PostInput
        type: object
        properties:
            description:
                type: string
                description: 説明
                example: 説明
                minLength: 1
            title:
                type: string
                description: タイトル
                example: タイトル
                minLength: 1
        example:
            description: 説明
            title: タイトル
    PostsDeleteNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: 記事が見つかりません (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PostsShowNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: show_not_found_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PostsUpdateNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: 記事が見つかりません (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PostsUpdateRequestBody:
        title: PostsUpdateRequestBody
        type: object
        properties:
            description:
                type: string
                description: 説明
                example: 説明
                minLength: 1
            title:
                type: string
                description: タイトル
                example: タイトル
                minLength: 1
        example:
            description: 説明
            title: タイトル
